

-- CREATE TABLE trainer (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     username VARCHAR(55) UNIQUE NOT NULL,
--     firstname VARCHAR(55) NOT NULL,
--     lastname VARCHAR(55) NOT NULL,
--     is_active BOOLEAN DEFAULT FALSE
--
-- );
--
-- CREATE TABLE training (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     trainer_id INT8 NOT NULL,
--     training_date DATE DEFAULT CURRENT_DATE,
--     training_duration INT4 NOT NULL,
--     action_type ENUM('ADD', 'DELETE') CHECK (action_type in ('ADD', 'DELETE')),
--     FOREIGN KEY (trainer_id) REFERENCES trainer(id)
--
-- );
--
-- CREATE TABLE trainer_workload (
--     id BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
--     trainer_id INT8 NOT NULL,
--     years INTEGER NOT NULL,
--     months INTEGER NOT NULL,
--     training_hours INTEGER NOT NULL,
--     FOREIGN KEY (trainer_id) REFERENCES trainer(id)
-- );
--
--
--
--
--
--
--
--
